package beyou.beyouapp.backend.tools;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.Container.ExecResult;
import org.testcontainers.postgresql.PostgreSQLContainer;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Baseline factory: regenerates {@code src/main/resources/db/migration/V1__baseline.sql}
 * from the current entity mappings, using a throwaway Postgres container.
 *
 * <p>It never touches the dev database, so the baseline can't inherit drift
 * accumulated by years of {@code ddl-auto: update}. Re-runnable on any machine
 * with Docker.
 *
 * <p>Not part of the normal suite — run explicitly via
 * {@code scripts/generate-baseline.sh} (which sets {@code -Dbaseline.generate=true}).
 *
 * <p>Policy: migration immutability begins at first production deploy. Until
 * then the chain may be squashed back into a regenerated V1 via this tool
 * (tag the repo when you do). After first prod deploy, never regenerate — write
 * new versioned migrations instead.
 */
@SpringBootTest
@ActiveProfiles("test")
@EnabledIfSystemProperty(named = "baseline.generate", matches = "true")
class BaselineGeneratorTest {

    static final PostgreSQLContainer POSTGRES =
            new PostgreSQLContainer("postgres:15")
                    .withDatabaseName("baseline")
                    .withUsername("baseline")
                    .withPassword("baseline");

    static {
        POSTGRES.start();
    }

    @DynamicPropertySource
    static void cleanRoomSchemaGeneration(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", POSTGRES::getJdbcUrl);
        registry.add("spring.datasource.username", POSTGRES::getUsername);
        registry.add("spring.datasource.password", POSTGRES::getPassword);
        registry.add("spring.datasource.driver-class-name", () -> "org.postgresql.Driver");
        // The one sanctioned use of Hibernate DDL after the Flyway cutover:
        // generating the schema this baseline snapshots.
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "create");
        registry.add("spring.flyway.enabled", () -> "false");
    }

    @Test
    void generateBaseline() throws Exception {
        ExecResult dump = POSTGRES.execInContainer(
                "pg_dump", "--schema-only", "--no-owner", "--no-privileges",
                "-U", POSTGRES.getUsername(), "baseline");
        assertThat(dump.getExitCode()).as(dump.getStderr()).isZero();

        String cleaned = clean(dump.getStdout());
        assertThat(cleaned).contains("CREATE TABLE");

        Path target = Path.of("src/main/resources/db/migration/V1__baseline.sql");
        Files.createDirectories(target.getParent());
        Files.writeString(target,
                "-- Generated by BaselineGeneratorTest (scripts/generate-baseline.sh)\n"
                + "-- from the JPA entity mappings via Hibernate ddl-auto=create on postgres:15.\n"
                + "-- Do not hand-edit: regenerate instead (allowed until first prod deploy).\n\n"
                + cleaned);
    }

    /**
     * Strips pg_dump noise (SET statements, psql meta-commands, comments,
     * schema boilerplate) so the migration is deterministic and reviewable.
     */
    private static String clean(String raw) {
        List<String> kept = new ArrayList<>();
        boolean lastBlank = false;
        for (String line : raw.split("\n", -1)) {
            String trimmed = line.strip();
            if (trimmed.startsWith("--")
                    || trimmed.startsWith("SET ")
                    || trimmed.startsWith("\\restrict")
                    || trimmed.startsWith("\\unrestrict")
                    || trimmed.startsWith("SELECT pg_catalog.set_config")
                    || trimmed.startsWith("CREATE SCHEMA public")
                    || trimmed.startsWith("COMMENT ON SCHEMA public")) {
                continue;
            }
            boolean blank = trimmed.isEmpty();
            if (blank && lastBlank) {
                continue;
            }
            kept.add(blank ? "" : line);
            lastBlank = blank;
        }
        return String.join("\n", kept).strip() + "\n";
    }
}
