-- Generated by BaselineGeneratorTest (scripts/generate-baseline.sh)
-- from the JPA entity mappings via Hibernate ddl-auto=create on postgres:15.
-- Do not hand-edit: regenerate instead (allowed until first prod deploy).

CREATE TABLE public.base_checks (
    check_date date,
    check_time time(0) without time zone,
    checked boolean NOT NULL,
    skipped boolean,
    xp_generated double precision NOT NULL,
    id uuid NOT NULL
);

CREATE TABLE public.categories (
    actual_level_xp double precision,
    created_at date,
    level integer,
    next_level_xp double precision,
    updated_at date,
    xp double precision,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    description character varying(256),
    name character varying(256) NOT NULL,
    icon_id character varying(255) NOT NULL
);

CREATE TABLE public.docs_api_controller_content (
    updated_at date NOT NULL,
    locale character varying(8) NOT NULL,
    id uuid NOT NULL,
    topic_id uuid NOT NULL,
    api_catalog text NOT NULL,
    summary text,
    title character varying(255) NOT NULL
);

CREATE TABLE public.docs_api_controller_topic (
    created_at date NOT NULL,
    order_index integer NOT NULL,
    updated_at date NOT NULL,
    id uuid NOT NULL,
    key character varying(128) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT docs_api_controller_topic_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DRAFT'::character varying, 'ARCHIVED'::character varying])::text[])))
);

CREATE TABLE public.docs_architecture_topic (
    created_at date NOT NULL,
    order_index integer NOT NULL,
    updated_at date NOT NULL,
    id uuid NOT NULL,
    key character varying(128) NOT NULL,
    project_key character varying(128),
    status character varying(255) NOT NULL,
    tags text,
    CONSTRAINT docs_architecture_topic_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DRAFT'::character varying, 'ARCHIVED'::character varying])::text[])))
);

CREATE TABLE public.docs_architecture_topic_content (
    updated_at date NOT NULL,
    locale character varying(8) NOT NULL,
    id uuid NOT NULL,
    topic_id uuid NOT NULL,
    diagram_mermaid text NOT NULL,
    doc_markdown text NOT NULL,
    summary text,
    title character varying(255) NOT NULL
);

CREATE TABLE public.docs_blog_topic (
    created_at date NOT NULL,
    featured boolean NOT NULL,
    published_at date,
    updated_at date NOT NULL,
    id uuid NOT NULL,
    key character varying(128) NOT NULL,
    author character varying(255),
    category character varying(255) NOT NULL,
    cover_color character varying(255),
    cover_emoji character varying(255),
    status character varying(255) NOT NULL,
    tags text,
    CONSTRAINT docs_blog_topic_category_check CHECK (((category)::text = ANY ((ARRAY['TECHNICAL'::character varying, 'PLANNING'::character varying])::text[]))),
    CONSTRAINT docs_blog_topic_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ARCHIVED'::character varying])::text[])))
);

CREATE TABLE public.docs_blog_topic_content (
    updated_at date NOT NULL,
    locale character varying(8) NOT NULL,
    id uuid NOT NULL,
    topic_id uuid NOT NULL,
    doc_markdown text NOT NULL,
    summary text,
    title character varying(255) NOT NULL
);

CREATE TABLE public.docs_project_topic (
    created_at date NOT NULL,
    order_index integer NOT NULL,
    updated_at date NOT NULL,
    id uuid NOT NULL,
    key character varying(128) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT docs_project_topic_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DRAFT'::character varying, 'ARCHIVED'::character varying, 'PLANNING'::character varying])::text[])))
);

CREATE TABLE public.docs_project_topic_content (
    updated_at date NOT NULL,
    locale character varying(8) NOT NULL,
    id uuid NOT NULL,
    topic_id uuid NOT NULL,
    architecture_topic_key character varying(128),
    design_topic_key character varying(128),
    diagram_mermaid text,
    doc_markdown text NOT NULL,
    repository_url text,
    summary text,
    tags text,
    title character varying(255) NOT NULL
);

CREATE TABLE public.goal_category (
    category_id uuid NOT NULL,
    goal_id uuid NOT NULL
);

CREATE TABLE public.goals (
    complete boolean NOT NULL,
    complete_date date,
    current_value double precision NOT NULL,
    end_date date NOT NULL,
    start_date date NOT NULL,
    target_value double precision NOT NULL,
    xp_reward double precision NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    description character varying(255),
    icon_id character varying(255) NOT NULL,
    motivation character varying(255),
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    term character varying(255) NOT NULL,
    unit character varying(255) NOT NULL,
    CONSTRAINT goals_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT goals_term_check CHECK (((term)::text = ANY ((ARRAY['SHORT_TERM'::character varying, 'MEDIUM_TERM'::character varying, 'LONG_TERM'::character varying])::text[])))
);

CREATE TABLE public.habit_category (
    category_id uuid NOT NULL,
    habit_id uuid NOT NULL
);

CREATE TABLE public.habit_group_checks (
    habit_group_id uuid NOT NULL,
    id uuid NOT NULL
);

CREATE TABLE public.habit_groups (
    habit_id uuid NOT NULL,
    id uuid NOT NULL
);

CREATE TABLE public.habits (
    actual_level_xp double precision,
    constance integer,
    created_at date NOT NULL,
    dificulty integer NOT NULL,
    importance integer NOT NULL,
    level integer,
    next_level_xp double precision,
    updated_at date NOT NULL,
    xp double precision,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    description character varying(256),
    motivational_phrase character varying(256),
    name character varying(256) NOT NULL,
    icon_id character varying(255) NOT NULL
);

CREATE TABLE public.item_groups (
    end_time time(0) without time zone,
    start_time time(0) without time zone,
    id uuid NOT NULL,
    routine_section_id uuid
);

CREATE TABLE public.password_reset_tokens (
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    used_at timestamp(6) without time zone,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash character varying(255) NOT NULL
);

CREATE TABLE public.refresh_tokens (
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    revoked_at timestamp(6) without time zone,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token_hash character varying(255)
);

CREATE TABLE public.routine_sections (
    end_time time(0) without time zone,
    favorite boolean,
    order_index integer,
    start_time time(0) without time zone,
    id uuid NOT NULL,
    routine_id uuid,
    icon_id character varying(255),
    name character varying(255) NOT NULL
);

CREATE TABLE public.routine_sections_habit_groups (
    habit_groups_id uuid NOT NULL,
    routine_section_id uuid NOT NULL
);

CREATE TABLE public.routine_sections_task_groups (
    routine_section_id uuid NOT NULL,
    task_groups_id uuid NOT NULL
);

CREATE TABLE public.routine_snapshot (
    completed boolean NOT NULL,
    snapshot_date date NOT NULL,
    id uuid NOT NULL,
    routine_id uuid NOT NULL,
    user_id uuid NOT NULL,
    routine_icon_id character varying(255),
    routine_name character varying(255) NOT NULL,
    structure_json text NOT NULL
);

CREATE TABLE public.routines (
    actual_level_xp double precision,
    level integer,
    next_level_xp double precision,
    xp double precision,
    id uuid NOT NULL,
    schedule_id uuid,
    user_id uuid NOT NULL,
    dtype character varying(31) NOT NULL,
    icon_id character varying(255),
    name character varying(255) NOT NULL,
    CONSTRAINT routines_dtype_check CHECK (((dtype)::text = 'DiaryRoutine'::text))
);

CREATE TABLE public.schedule_days (
    schedule_id uuid NOT NULL,
    days character varying(20) NOT NULL,
    CONSTRAINT schedule_days_days_check CHECK (((days)::text = ANY ((ARRAY['Monday'::character varying, 'Tuesday'::character varying, 'Wednesday'::character varying, 'Thursday'::character varying, 'Friday'::character varying, 'Saturday'::character varying, 'Sunday'::character varying])::text[])))
);

CREATE TABLE public.schedules (
    id uuid NOT NULL
);

CREATE TABLE public.snapshot_check (
    check_time time(0) without time zone,
    checked boolean NOT NULL,
    difficulty integer NOT NULL,
    importance integer NOT NULL,
    skipped boolean NOT NULL,
    xp_generated double precision NOT NULL,
    id uuid NOT NULL,
    original_group_id uuid,
    original_item_id uuid,
    snapshot_id uuid NOT NULL,
    item_icon_id character varying(255),
    item_name character varying(255) NOT NULL,
    item_type character varying(255) NOT NULL,
    section_name character varying(255) NOT NULL,
    CONSTRAINT snapshot_check_item_type_check CHECK (((item_type)::text = ANY ((ARRAY['HABIT'::character varying, 'TASK'::character varying])::text[])))
);

CREATE TABLE public.task_category (
    category_id uuid NOT NULL,
    task_id uuid NOT NULL
);

CREATE TABLE public.task_group_checks (
    id uuid NOT NULL,
    task_group_id uuid NOT NULL
);

CREATE TABLE public.task_groups (
    id uuid NOT NULL,
    task_id uuid NOT NULL
);

CREATE TABLE public.tasks (
    created_at date NOT NULL,
    dificulty integer,
    importance integer,
    marked_to_delete date,
    one_time_task boolean NOT NULL,
    updated_at date NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    description character varying(255),
    icon_id character varying(255),
    name character varying(255)
);

CREATE TABLE public.users (
    actual_level_xp double precision,
    created_at date,
    email_verified boolean DEFAULT false NOT NULL,
    is_google_account boolean NOT NULL,
    is_tutorial_completed boolean NOT NULL,
    level integer,
    max_constance integer,
    next_level_xp double precision,
    updated_at date,
    xp double precision,
    verification_token_expiry timestamp(6) without time zone,
    id uuid NOT NULL,
    constance_configuration character varying(255),
    email character varying(255) NOT NULL,
    language_in_use character varying(255),
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    perfil_photo character varying(255),
    perfil_phrase character varying(255),
    perfil_phrase_author character varying(255),
    theme_in_use character varying(255),
    timezone character varying(255) NOT NULL,
    user_role character varying(255),
    verification_token character varying(255),
    xp_decay_strategy character varying(255) NOT NULL,
    completed_days date[],
    tasks character varying(255)[],
    widgets_id_in_use character varying(255)[],
    CONSTRAINT users_constance_configuration_check CHECK (((constance_configuration)::text = ANY ((ARRAY['ANY'::character varying, 'COMPLETE'::character varying])::text[]))),
    CONSTRAINT users_user_role_check CHECK (((user_role)::text = 'USER'::text)),
    CONSTRAINT users_xp_decay_strategy_check CHECK (((xp_decay_strategy)::text = ANY ((ARRAY['GRADUAL'::character varying, 'FLAT'::character varying, 'TIME_WINDOW'::character varying])::text[])))
);

CREATE TABLE public.xp_by_level (
    level integer NOT NULL,
    xp double precision
);

ALTER TABLE ONLY public.base_checks
    ADD CONSTRAINT base_checks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_api_controller_content
    ADD CONSTRAINT docs_api_controller_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_api_controller_content
    ADD CONSTRAINT docs_api_controller_content_topic_id_locale_key UNIQUE (topic_id, locale);

ALTER TABLE ONLY public.docs_api_controller_topic
    ADD CONSTRAINT docs_api_controller_topic_key_key UNIQUE (key);

ALTER TABLE ONLY public.docs_api_controller_topic
    ADD CONSTRAINT docs_api_controller_topic_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_architecture_topic_content
    ADD CONSTRAINT docs_architecture_topic_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_architecture_topic_content
    ADD CONSTRAINT docs_architecture_topic_content_topic_id_locale_key UNIQUE (topic_id, locale);

ALTER TABLE ONLY public.docs_architecture_topic
    ADD CONSTRAINT docs_architecture_topic_key_key UNIQUE (key);

ALTER TABLE ONLY public.docs_architecture_topic
    ADD CONSTRAINT docs_architecture_topic_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_blog_topic_content
    ADD CONSTRAINT docs_blog_topic_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_blog_topic_content
    ADD CONSTRAINT docs_blog_topic_content_topic_id_locale_key UNIQUE (topic_id, locale);

ALTER TABLE ONLY public.docs_blog_topic
    ADD CONSTRAINT docs_blog_topic_key_key UNIQUE (key);

ALTER TABLE ONLY public.docs_blog_topic
    ADD CONSTRAINT docs_blog_topic_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_project_topic_content
    ADD CONSTRAINT docs_project_topic_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.docs_project_topic_content
    ADD CONSTRAINT docs_project_topic_content_topic_id_locale_key UNIQUE (topic_id, locale);

ALTER TABLE ONLY public.docs_project_topic
    ADD CONSTRAINT docs_project_topic_key_key UNIQUE (key);

ALTER TABLE ONLY public.docs_project_topic
    ADD CONSTRAINT docs_project_topic_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.habit_group_checks
    ADD CONSTRAINT habit_group_checks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.habit_groups
    ADD CONSTRAINT habit_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT habits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.item_groups
    ADD CONSTRAINT item_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routine_sections_habit_groups
    ADD CONSTRAINT routine_sections_habit_groups_habit_groups_id_key UNIQUE (habit_groups_id);

ALTER TABLE ONLY public.routine_sections
    ADD CONSTRAINT routine_sections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routine_sections_task_groups
    ADD CONSTRAINT routine_sections_task_groups_task_groups_id_key UNIQUE (task_groups_id);

ALTER TABLE ONLY public.routine_snapshot
    ADD CONSTRAINT routine_snapshot_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routine_snapshot
    ADD CONSTRAINT routine_snapshot_routine_id_snapshot_date_key UNIQUE (routine_id, snapshot_date);

ALTER TABLE ONLY public.routines
    ADD CONSTRAINT routines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routines
    ADD CONSTRAINT routines_schedule_id_key UNIQUE (schedule_id);

ALTER TABLE ONLY public.schedule_days
    ADD CONSTRAINT schedule_days_schedule_id_days_key UNIQUE (schedule_id, days);

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.snapshot_check
    ADD CONSTRAINT snapshot_check_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.task_group_checks
    ADD CONSTRAINT task_group_checks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.task_groups
    ADD CONSTRAINT task_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.xp_by_level
    ADD CONSTRAINT xp_by_level_pkey PRIMARY KEY (level);

CREATE INDEX idx_snapshot_check_snapshot ON public.snapshot_check USING btree (snapshot_id);

CREATE INDEX idx_snapshot_routine_date ON public.routine_snapshot USING btree (routine_id, snapshot_date);

CREATE INDEX idx_snapshot_user_routine_date ON public.routine_snapshot USING btree (user_id, routine_id, snapshot_date);

ALTER TABLE ONLY public.routine_snapshot
    ADD CONSTRAINT fk11lccstqbj98y6f9jv79ytdy7 FOREIGN KEY (routine_id) REFERENCES public.routines(id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.routine_sections_task_groups
    ADD CONSTRAINT fk26nil6vg4pjn826w4dn5w7nv FOREIGN KEY (routine_section_id) REFERENCES public.routine_sections(id);

ALTER TABLE ONLY public.task_category
    ADD CONSTRAINT fk3w86x4qd6yca181wg1eo3y6ye FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.habit_groups
    ADD CONSTRAINT fk5gftnuluiketdcp48ilkvs6fd FOREIGN KEY (id) REFERENCES public.item_groups(id);

ALTER TABLE ONLY public.habit_group_checks
    ADD CONSTRAINT fk5kgkpgv24j5kgw67wouf03buq FOREIGN KEY (id) REFERENCES public.base_checks(id);

ALTER TABLE ONLY public.habit_group_checks
    ADD CONSTRAINT fk69lii9dolubonvs7ixg08vp04 FOREIGN KEY (habit_group_id) REFERENCES public.habit_groups(id);

ALTER TABLE ONLY public.task_groups
    ADD CONSTRAINT fk6c09ydwgjydenrsjnijwuej3y FOREIGN KEY (task_id) REFERENCES public.tasks(id);

ALTER TABLE ONLY public.task_category
    ADD CONSTRAINT fk6il0o73v6nokyn1jeg2nhh655 FOREIGN KEY (task_id) REFERENCES public.tasks(id);

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fk6s1ob9k4ihi75xbxe2w0ylsdh FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.task_group_checks
    ADD CONSTRAINT fk85mp19pn5juy7cpikm9ltfd18 FOREIGN KEY (task_group_id) REFERENCES public.task_groups(id);

ALTER TABLE ONLY public.routine_sections
    ADD CONSTRAINT fk8h0obxxwfk88q7j33yqlhuvs0 FOREIGN KEY (routine_id) REFERENCES public.routines(id);

ALTER TABLE ONLY public.docs_architecture_topic_content
    ADD CONSTRAINT fkadbr7u73uepd59ue0mjemj48e FOREIGN KEY (topic_id) REFERENCES public.docs_architecture_topic(id);

ALTER TABLE ONLY public.habit_groups
    ADD CONSTRAINT fkakvr2mtpjr7b55i7e8yny0908 FOREIGN KEY (habit_id) REFERENCES public.habits(id);

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT fkb1mp6ulyqkpcw6bc1a2mr7v1g FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.habit_category
    ADD CONSTRAINT fkbcxrtud7fm4yl4tspct6tfkra FOREIGN KEY (habit_id) REFERENCES public.habits(id);

ALTER TABLE ONLY public.goal_category
    ADD CONSTRAINT fkbnpdk0vfmswel3lwa1guf717d FOREIGN KEY (goal_id) REFERENCES public.goals(id);

ALTER TABLE ONLY public.task_groups
    ADD CONSTRAINT fkcfaxrhdy86b1nca12t80tw3j1 FOREIGN KEY (id) REFERENCES public.item_groups(id);

ALTER TABLE ONLY public.docs_blog_topic_content
    ADD CONSTRAINT fkdml5oi1hkqw5v1w3b8cvcbfd2 FOREIGN KEY (topic_id) REFERENCES public.docs_blog_topic(id);

ALTER TABLE ONLY public.schedule_days
    ADD CONSTRAINT fkfjqqji6gtqyp0e4k8ot0l7g7d FOREIGN KEY (schedule_id) REFERENCES public.schedules(id);

ALTER TABLE ONLY public.habit_category
    ADD CONSTRAINT fkfnjn2ps544xsv2codl6b0twc5 FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.habits
    ADD CONSTRAINT fkg3n2qqwmsyv3517xdcosouk9i FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.goal_category
    ADD CONSTRAINT fkg3na665s3qpupiok0fb6gsy6w FOREIGN KEY (category_id) REFERENCES public.categories(id);

ALTER TABLE ONLY public.task_group_checks
    ADD CONSTRAINT fkg68sqhhbspewn2o548fbys0ti FOREIGN KEY (id) REFERENCES public.base_checks(id);

ALTER TABLE ONLY public.routine_sections_habit_groups
    ADD CONSTRAINT fkggkkopf8pu1sqj9yt7k0948wu FOREIGN KEY (routine_section_id) REFERENCES public.routine_sections(id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fkghuylkwuedgl2qahxjt8g41kb FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.snapshot_check
    ADD CONSTRAINT fkgjbwpgptcfga40asgr2iilwdq FOREIGN KEY (snapshot_id) REFERENCES public.routine_snapshot(id);

ALTER TABLE ONLY public.routines
    ADD CONSTRAINT fkh4inbdvv6paby7lv68824f5yq FOREIGN KEY (schedule_id) REFERENCES public.schedules(id);

ALTER TABLE ONLY public.routine_sections_task_groups
    ADD CONSTRAINT fkjt5ao51ws3euyk3aq2svgmw3p FOREIGN KEY (task_groups_id) REFERENCES public.task_groups(id);

ALTER TABLE ONLY public.docs_api_controller_content
    ADD CONSTRAINT fkjuhctybywaypilm7sc6ajyccq FOREIGN KEY (topic_id) REFERENCES public.docs_api_controller_topic(id);

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkk3ndxg5xp6v7wd4gjyusp15gq FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.routine_sections_habit_groups
    ADD CONSTRAINT fkkln5u3wn1kd44h0530qflbgex FOREIGN KEY (habit_groups_id) REFERENCES public.habit_groups(id);

ALTER TABLE ONLY public.routines
    ADD CONSTRAINT fklsu2ed1i9h7w7j9i3t5nhqyka FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.item_groups
    ADD CONSTRAINT fkp38marbrh5fxvbetqeiuag9jf FOREIGN KEY (routine_section_id) REFERENCES public.routine_sections(id);

ALTER TABLE ONLY public.routine_snapshot
    ADD CONSTRAINT fkqwefrx021dwhj42dsqkrotg2c FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.docs_project_topic_content
    ADD CONSTRAINT fkrmhqwbn9a2biwpov8a8byyiph FOREIGN KEY (topic_id) REFERENCES public.docs_project_topic(id);
