package beyou.beyouapp.backend.unit.security;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import java.sql.Timestamp;
import java.time.Duration;
import java.util.Optional;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import beyou.beyouapp.backend.exceptions.security.RefreshTokenDontMatchRaw;
import beyou.beyouapp.backend.exceptions.security.RefreshTokenExpiredException;
import beyou.beyouapp.backend.exceptions.security.RefreshTokenNotFoundException;
import org.springframework.http.ResponseCookie;
import beyou.beyouapp.backend.monitoring.UserActivityTracker;
import beyou.beyouapp.backend.security.TokenService;
import beyou.beyouapp.backend.security.RefreshToken.RefreshToken;
import beyou.beyouapp.backend.security.RefreshToken.RefreshTokenRepository;
import beyou.beyouapp.backend.security.RefreshToken.RefreshTokenService;
import beyou.beyouapp.backend.user.User;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@ExtendWith(MockitoExtension.class)
public class RefreshTokenServiceUnitTest {

    @Mock
    private RefreshTokenRepository repository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @Mock
    private TokenService tokenService;

    @Mock
    private HttpServletRequest request;

    @Mock
    private HttpServletResponse response;

    @Mock
    private UserActivityTracker userActivityTracker;

    @InjectMocks
    private RefreshTokenService refreshTokenService;

    /** A row written before the SHA-256 switch. Only BCrypt hashes start with $2. */
    static final String LEGACY_BCRYPT_HASH = "$2a$12$legacyBcryptHashWrittenBeforeTheSwitch";

    RefreshToken refreshToken = new RefreshToken();
    UUID userId = UUID.randomUUID();
    UUID tokenId = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        refreshToken.setId(tokenId);
        refreshToken.setTokenHash(LEGACY_BCRYPT_HASH);
        refreshToken.setExpiresAt(new Timestamp(System.currentTimeMillis() + 100000)); // expires in the future
        // The rotation path issues a new token for the token's owner, which now also
        // records login activity — so the fixture needs an owner with an id.
        User owner = new User();
        owner.setId(userId);
        refreshToken.setUser(owner);
    }

    /** The id is generated by the database; a mocked repository has to play that part. */
    private void saveAssignsIds() {
        when(repository.save(any(RefreshToken.class))).thenAnswer(inv -> {
            RefreshToken t = inv.getArgument(0);
            if (t.getId() == null) t.setId(UUID.randomUUID());
            return t;
        });
    }

    @Nested
    public class happyPath {
        @Test
        void createRefreshTokenStoresASha256HashAndNeverTouchesBcrypt() {
            // Given
            var user = new User();
            user.setId(userId);
            ArgumentCaptor<RefreshToken> saved = ArgumentCaptor.forClass(RefreshToken.class);

            // When
            String result = refreshTokenService.createRefreshToken(user);

            // Then
            String[] parts = result.split("\\.");
            assertEquals(2, parts.length);
            verify(repository).save(saved.capture());
            String stored = saved.getValue().getTokenHash();
            assertTrue(stored.startsWith("sha256:"), stored);
            assertEquals("sha256:".length() + 64, stored.length());
            assertFalse(stored.contains(parts[1]), "the raw token must not be stored");
            // BCrypt(12) is ~400 ms on the prod box; issuing a token must not pay it.
            verifyNoInteractions(passwordEncoder);
        }

        @Test
        void aTokenIssuedNowIsAcceptedOnRefreshWithoutBcrypt() {
            // Given: issue a token and keep the row it would have written
            saveAssignsIds();
            var user = new User();
            user.setId(userId);
            ArgumentCaptor<RefreshToken> saved = ArgumentCaptor.forClass(RefreshToken.class);
            String issued = refreshTokenService.createRefreshToken(user);
            verify(repository).save(saved.capture());
            RefreshToken row = saved.getValue();

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", issued) });
            when(repository.findById(row.getId())).thenReturn(Optional.of(row));

            // When / Then
            assertDoesNotThrow(() -> refreshTokenService.refreshAccessToken(request, response));
            assertNotNull(row.getRevokedAt());
            verifyNoInteractions(passwordEncoder);
        }

        @Test
        void aLegacyBcryptRowIsRotatedOntoSha256() {
            // Given
            String rawToken = "rawToken";
            when(request.getCookies()).thenReturn(new Cookie[] {
                    new Cookie("refreshToken", tokenId + "." + rawToken) });
            when(repository.findById(tokenId)).thenReturn(Optional.of(refreshToken));
            when(passwordEncoder.matches(rawToken, LEGACY_BCRYPT_HASH)).thenReturn(true);
            ArgumentCaptor<RefreshToken> saved = ArgumentCaptor.forClass(RefreshToken.class);

            // When
            refreshTokenService.refreshAccessToken(request, response);

            // Then: old row revoked, new row written as SHA-256
            verify(repository, times(2)).save(saved.capture());
            assertNotNull(saved.getAllValues().get(0).getRevokedAt());
            assertTrue(saved.getAllValues().get(1).getTokenHash().startsWith("sha256:"));
            verify(passwordEncoder, never()).encode(anyString());
        }

        @Test
        void testRefreshAccessToken() {
            // Given
            String rawToken = "rawToken";
            String cookieValue = tokenId.toString() + "." + rawToken;

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", cookieValue) });
            when(repository.findById(tokenId)).thenReturn(Optional.of(refreshToken));
            when(passwordEncoder.matches(rawToken, refreshToken.getTokenHash())).thenReturn(true);

            // Then
            assertDoesNotThrow(() -> refreshTokenService.refreshAccessToken(request, response));
            // Here the token is already revoked because of the last call
            assertThrows(RefreshTokenExpiredException.class,
                    () -> refreshTokenService.refreshAccessToken(request, response));
            verify(repository, times(2)).findById(tokenId);
            verify(passwordEncoder, times(2)).matches(rawToken, refreshToken.getTokenHash());
        }

        @Test
        void shouldReturnTrueIfTokenIsExpired() {
            // Given
            refreshToken.setExpiresAt(new Timestamp(System.currentTimeMillis() - 100000)); // expired in the past

            // When
            boolean isExpired = refreshTokenService.isTokenExpired(refreshToken);

            // Then
            assertEquals(true, isExpired);
        }

        @Test
        void testRevokeRefreshToken() {
            // Given
            String cookieValue = tokenId.toString() + ".rawToken";
            ResponseCookie clearCookie = ResponseCookie.from("refreshToken", "")
                    .httpOnly(true).path("/").maxAge(Duration.ZERO).build();

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", cookieValue) });
            when(repository.findById(tokenId)).thenReturn(Optional.of(refreshToken));
            when(passwordEncoder.matches("rawToken", refreshToken.getTokenHash())).thenReturn(true);
            when(tokenService.buildRefreshCookie("", Duration.ZERO)).thenReturn(clearCookie);

            // When
            refreshTokenService.revokeRefreshToken(request, response);

            // Then
            verify(repository).save(refreshToken);
            verify(response).addHeader("Set-Cookie", clearCookie.toString());
        }

    }

    @Nested
    public class exceptions {

        @Test
        void testRefreshAccessTokenWithMalformedToken() {
            // Given
            String cookieValue = "malformedToken";

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", cookieValue) });

            // Then
            assertThrows(RefreshTokenNotFoundException.class,
                    () -> refreshTokenService.refreshAccessToken(request, response));
        }

        @Test
        void testRefreshAccessTokenWithNonExistingToken() {
            // Given
            String rawToken = "rawToken";
            String cookieValue = tokenId.toString() + "." + rawToken;

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", cookieValue) });
            when(repository.findById(tokenId)).thenReturn(Optional.empty());

            // Then
            assertThrows(RefreshTokenNotFoundException.class,
                    () -> refreshTokenService.refreshAccessToken(request, response));
        }

        @Test
        void testRefreshAccessTokenWithNonMatchingRawToken() {
            // Given
            String rawToken = "rawToken";
            String cookieValue = tokenId.toString() + "." + rawToken;

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", cookieValue) });
            when(repository.findById(tokenId)).thenReturn(Optional.of(refreshToken));
            when(passwordEncoder.matches(rawToken, refreshToken.getTokenHash())).thenReturn(false);

            // Then
            assertThrows(RefreshTokenDontMatchRaw.class,
                    () -> refreshTokenService.refreshAccessToken(request, response));
        }

        @Test
        void aSha256RowRejectsADifferentRawToken() {
            // Given: a row holding the hash of one token, presented with another
            saveAssignsIds();
            var user = new User();
            user.setId(userId);
            ArgumentCaptor<RefreshToken> saved = ArgumentCaptor.forClass(RefreshToken.class);
            String issued = refreshTokenService.createRefreshToken(user);
            verify(repository).save(saved.capture());
            RefreshToken row = saved.getValue();
            UUID id = row.getId();
            String tampered = id + "." + issued.split("\\.")[1] + "x";

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", tampered) });
            when(repository.findById(id)).thenReturn(Optional.of(row));

            // Then
            assertThrows(RefreshTokenDontMatchRaw.class,
                    () -> refreshTokenService.refreshAccessToken(request, response));
            verifyNoInteractions(passwordEncoder);
        }

        @Test
        void shouldThrowTokenExpired() {
            // Given
            refreshToken.setExpiresAt(new Timestamp(System.currentTimeMillis() - 100000)); // expired in the past
            String rawToken = "rawToken";
            String cookieValue = tokenId.toString() + "." + rawToken;

            when(request.getCookies()).thenReturn(new Cookie[] { new Cookie("refreshToken", cookieValue) });
            when(repository.findById(tokenId)).thenReturn(Optional.of(refreshToken));
            when(passwordEncoder.matches(rawToken, refreshToken.getTokenHash())).thenReturn(true);

            // Then
            assertThrows(RefreshTokenExpiredException.class,
                    () -> refreshTokenService.refreshAccessToken(request, response));
        }
    }
}